# helpers/validation/__init__.py
# Public validation package façade. Prefer importing from here for a stable, explicit API surface.

from .errors import ValidationError, qpath, type_name
from .scalars import (
    ensure_bool,
    ensure_dict,
    ensure_dict_of_str,
    ensure_enum_name,
    ensure_float,
    ensure_int,
    ensure_ip,
    ensure_list,
    ensure_list_of_dicts,
    ensure_list_of_str,
    ensure_non_empty_list,
    ensure_one_of,
    ensure_pathlike,
    ensure_regex,
    ensure_str,
    ensure_unique,
)
from .net import (
    ensure_endpoint,
    ensure_host,
    ensure_http_url,
    ensure_port,
)
from .mapping import (
    path_join,
    require_bool,
    require_dict_of_str,
    require_endpoint,
    require_float,
    require_host,
    require_http_url,
    require_int,
    require_ip,
    require_list_of_dicts,
    require_list_of_str,
    require_one_of,
    require_path,
    require_port,
    require_regex,
    require_str,
    optional_bool,
    optional_float,
    optional_int,
    optional_list_of_str,
    optional_path,
    optional_str,
)

__all__ = [
    # errors
    "ValidationError",
    "type_name",
    "qpath",
    # scalars
    "ensure_dict",
    "ensure_list",
    "ensure_non_empty_list",
    "ensure_str",
    "ensure_bool",
    "ensure_int",
    "ensure_float",
    "ensure_one_of",
    "ensure_list_of_dicts",
    "ensure_list_of_str",
    "ensure_dict_of_str",
    "ensure_unique",
    "ensure_ip",
    "ensure_pathlike",
    "ensure_enum_name",
    "ensure_regex",
    # net
    "ensure_port",
    "ensure_host",
    "ensure_endpoint",
    "ensure_http_url",
    # mapping readers
    "path_join",
    "require_str",
    "require_int",
    "require_float",
    "require_bool",
    "require_one_of",
    "require_list_of_dicts",
    "require_list_of_str",
    "require_dict_of_str",
    "require_path",
    "require_regex",
    "require_ip",
    "require_port",
    "require_host",
    "require_endpoint",
    "require_http_url",
    # optional readers
    "optional_str",
    "optional_int",
    "optional_float",
    "optional_bool",
    "optional_list_of_str",
    "optional_path",
]
